### ISSUE TITLE
Donnée "language du dépôt" erronnée ? 

### ISSUE THREAD

**Issue by SebastienTouze** [etalab/code.etalab.gouv.fr#82]
Hello

La recherche sur le langage utilisé semble confondre Java et JavaScript 
Par exemple : https://code.etalab.gouv.fr/fr/repos?language=Java sors plusieurs dépôts en Javascript (ex. pix < 1024pix ou standup < SocialGouv)
Ne faudrait-il pas supprimer l'auto-complétion ?

La recherche renvoie d'ailleurs 974 repos trouvés pour 309 dépôts réellement en Java

**Comment by bzg** [comment]
Salut @SebastienTouze, désolé pour la réponse tardive, et merci pour le rapport de bug.

C'est corrigé dans la version publiée aujourd'hui. Merci !
