### ISSUE TITLE
extraction de données filtrées

### ISSUE THREAD

**Issue by MayaAndersonGonzalez** [etalab/code.etalab.gouv.fr#83]
Le bouton 'csv' donne accès à l'intégralité des données mais ne prend pas en compte le filtrage. A terme ce serait top de pouvoir obtenir un csv contenant uniquement des données filtrées, tels qu'elles s'affichent suite à une requête sur le site.

**Comment by bzg** [comment]
Oui, tout à fait ! Je vais voir ce que je peux faire.

**Comment by bzg** [comment]
C'est fait !  Vous pouvez désormais télécharger un csv avec la liste filtrée de dépôts ou des organisations.  Désolé pour le temps de réaction.
