### ISSUE TITLE
Recherche des organisations

### ISSUE THREAD

**Issue by pachevalier** [etalab/code.etalab.gouv.fr#85]
En cherchant "peren" dans la vue organisation, rien ne remonte (https://code.etalab.gouv.fr/fr/groups?q=peren&platform=all) alors qu'en cherchant "peren" dans les repos (https://code.etalab.gouv.fr/fr/repos?q=peren&platform=all), j'obtiens bien les codes sources de l'organisation peren.

J'ai l'impression que le search sur la page groups n'indexe pas toutes les organisations.

**Comment by bzg** [comment]
Merci !  Il y a bien un problème que je décris dans l'issue ci-dessus : ce n'est pas un souci avec l'interface de recherche mais avec les données collectées en amont.  Je ferme l'issue ici, elle sera corrigée dans l'autre dépôt.
